services:
  baseline-awareness:
    build:
      context: .
      dockerfile: Generated/Server/baseline-awareness/Dockerfile
  bootstrap:
    build:
      context: .
      dockerfile: Generated/Server/bootstrap/Dockerfile
  function-caller:
    build:
      context: .
      dockerfile: Generated/Server/function-caller/Dockerfile
  llm-gateway:
    build:
      context: .
      dockerfile: Generated/Server/llm-gateway/Dockerfile
  planner:
    build:
      context: .
      dockerfile: Generated/Server/planner/Dockerfile
  persist:
    build:
      context: .
      dockerfile: Generated/Server/persist/Dockerfile
  tools-factory:
    build:
      context: .
      dockerfile: Generated/Server/tools-factory/Dockerfile
  typesense:
    build:
      context: .
      dockerfile: Generated/Server/typesense/Dockerfile

# Â© 2025 Contexter alias Benedikt Eickhoff ğŸ›¡ï¸ All rights reserved.
